name: "Release"

on:
  push:
    tags: v0.*

env:
  GODOT_RELEASE: 4.0.4

jobs:
  release:
    name: "Release"
    runs-on: ubuntu-latest
    permissions: write-all
    steps:
      - name: "Checkout"
        uses: actions/checkout@v3
      - name: "Export Project"
        id: export
        uses: firebelley/godot-export@v5.1.0
        with:
          archive_output: true
          godot_executable_download_url: https://downloads.tuxfamily.org/godotengine/${{ env.GODOT_RELEASE }}/Godot_v${{ env.GODOT_RELEASE }}-stable_linux.x86_64.zip
          godot_export_templates_download_url: https://downloads.tuxfamily.org/godotengine/${{ env.GODOT_RELEASE }}/Godot_v${{ env.GODOT_RELEASE }}-stable_export_templates.tpz
          relative_project_path: ./
      - name: "Publish Release Assets"
        uses: ncipollo/release-action@v1.12.0
        with:
          artifacts: ${{ steps.export.outputs.archive_directory }}/*
          tag: ${{ github.ref_name }}
          token: ${{ secrets.GITHUB_TOKEN }}
